replicaCount: 2

ingress:
  enabled: true
  host: staging.api.example.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

persistence:
  enabled: false
