# Python API Settings
pythonApp:
  replicaCount: 1

# Redis Settings
# Overriding base defaults for the development environment
redis:
  enabled: true
  persistence:
    enabled: false  # Dev usually doesn't need persistent storage for Redis

# Shared/Global Settings
ingress:
  enabled: true
  host: staging.api.example.com
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
