apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-link-service-to-redis-app-label
  template:
    metadata:
      labels:
        app: redis-link-service-to-redis-app-label
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command: ["redis-server"]
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: REDIS_PASSWORD
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
      {{- end }}
